/*
** EPITECH PROJECT, 2021
** strace
** File description:
** syscall_val
*/

#ifndef SYSCALL_VAL_H_
#define SYSCALL_VAL_H_

#define EXIT_SYSCALL 231
#define FUNC_MAX_LEN 50
#define MAX_SYSCALL_NUM 331
#define SYSCALL_MAXARGS 6

enum arg_type_e {
    INT,
    PTR,
    STR,
    NULLVAL
};

typedef struct entry_s
{
    const char *name;
    int nb_args;
    enum arg_type_e args_value[SYSCALL_MAXARGS];
    enum arg_type_e retval;
} entry_t;

static entry_t entries[] = {
    [0] = {
        .retval = INT,
        .name  = "read",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [1] = {
        .retval = INT,
        .name  = "write",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [2] = {
        .retval = INT,
        .name  = "open",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [3] = {
        .retval = INT,
        .name  = "close",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [4] = {
        .retval = INT,
        .name  = "stat",
        .args_value  = {STR, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [5] = {
        .retval = INT,
        .name  = "fstat",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [6] = {
        .retval = INT,
        .name  = "lstat",
        .args_value  = {STR, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [7] = {
        .retval = INT,
        .name  = "poll",
        .args_value  = {PTR, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [8] = {
        .retval = INT,
        .name  = "lseek",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [9] = {
        .retval = PTR,
        .name  = "mmap",
        .args_value  = {PTR, INT, INT, INT, INT, INT},
        .nb_args = 6,
    },
    [10] = {
        .retval = INT,
        .name  = "mprotect",
        .args_value  = {PTR, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [11] = {
        .retval = INT,
        .name  = "munmap",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [12] = {
        .retval = INT,
        .name  = "brk",
        .args_value  = {PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [13] = {
        .retval = INT,
        .name  = "rt_sigaction",
        .args_value  = {INT, PTR, PTR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [14] = {
        .retval = INT,
        .name  = "rt_sigprocmask",
        .args_value  = {INT, PTR, PTR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [15] = {
        .retval = INT,
        .name  = "rt_sigreturn",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [16] = {
        .retval = INT,
        .name  = "ioctl",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [17] = {
        .retval = INT,
        .name  = "pread64",
        .args_value  = {INT, STR, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [18] = {
        .retval = INT,
        .name  = "pwrite64",
        .args_value  = {INT, STR, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [19] = {
        .retval = INT,
        .name  = "readv",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [20] = {
        .retval = INT,
        .name  = "writev",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [21] = {
        .retval = INT,
        .name  = "access",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [22] = {
        .retval = INT,
        .name  = "pipe",
        .args_value  = {PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [23] = {
        .retval = INT,
        .name  = "select",
        .args_value  = {INT, PTR, PTR, PTR, PTR, NULLVAL},
        .nb_args = 5,
    },
    [24] = {
        .retval = INT,
        .name  = "sched_yield",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [25] = {
        .retval = INT,
        .name  = "mremap",
        .args_value  = {INT, INT, INT, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [26] = {
        .retval = INT,
        .name  = "msync",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [27] = {
        .retval = INT,
        .name  = "mincore",
        .args_value  = {INT, INT, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [28] = {
        .retval = INT,
        .name  = "madvise",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [29] = {
        .retval = INT,
        .name  = "shmget",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [30] = {
        .retval = INT,
        .name  = "shmat",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [31] = {
        .retval = INT,
        .name  = "shmctl",
        .args_value  = {INT, INT, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [32] = {
        .retval = INT,
        .name  = "dup",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [33] = {
        .retval = INT,
        .name  = "dup2",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [34] = {
        .retval = INT,
        .name  = "pause",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [35] = {
        .retval = INT,
        .name  = "nanosleep",
        .args_value  = {PTR, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [36] = {
        .retval = INT,
        .name  = "getitimer",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [37] = {
        .retval = INT,
        .name  = "alarm",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [38] = {
        .retval = INT,
        .name  = "setitimer",
        .args_value  = {INT, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [39] = {
        .retval = INT,
        .name  = "getpid",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [40] = {
        .retval = INT,
        .name  = "sendfile",
        .args_value  = {INT, INT, PTR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [41] = {
        .retval = INT,
        .name  = "socket",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [42] = {
        .retval = INT,
        .name  = "connect",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [43] = {
        .retval = INT,
        .name  = "accept",
        .args_value  = {INT, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [44] = {
        .retval = INT,
        .name  = "sendto",
        .args_value  = {INT, PTR, INT, INT, PTR, INT},
        .nb_args = 6,
    },
    [45] = {
        .retval = INT,
        .name  = "recvfrom",
        .args_value  = {INT, PTR, INT, INT, PTR, PTR},
        .nb_args = 6,
    },
    [46] = {
        .retval = INT,
        .name  = "sendmsg",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [47] = {
        .retval = INT,
        .name  = "recvmsg",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [48] = {
        .retval = INT,
        .name  = "shutdown",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [49] = {
        .retval = INT,
        .name  = "bind",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [50] = {
        .retval = INT,
        .name  = "listen",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [51] = {
        .retval = INT,
        .name  = "getsockname",
        .args_value  = {INT, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [52] = {
        .retval = INT,
        .name  = "getpeername",
        .args_value  = {INT, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [53] = {
        .retval = INT,
        .name  = "socketpair",
        .args_value  = {INT, INT, INT, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [54] = {
        .retval = INT,
        .name  = "setsockopt",
        .args_value  = {INT, INT, INT, STR, INT, NULLVAL},
        .nb_args = 5,
    },
    [55] = {
        .retval = INT,
        .name  = "getsockopt",
        .args_value  = {INT, INT, INT, STR, PTR, NULLVAL},
        .nb_args = 5,
    },
    [56] = {
        .retval = INT,
        .name  = "clone",
        .args_value  = {INT, INT, PTR, PTR, INT, NULLVAL},
        .nb_args = 5,
    },
    [57] = {
        .retval = INT,
        .name  = "fork",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [58] = {
        .retval = INT,
        .name  = "vfork",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [59] = {
        .retval = INT,
        .name  = "execve",
        .args_value  = {STR, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [60] = {
        .retval = INT,
        .name  = "exit",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [61] = {
        .retval = INT,
        .name  = "wait4",
        .args_value  = {INT, PTR, INT, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [62] = {
        .retval = INT,
        .name  = "kill",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [63] = {
        .retval = INT,
        .name  = "uname",
        .args_value  = {PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [64] = {
        .retval = INT,
        .name  = "semget",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [65] = {
        .retval = INT,
        .name  = "semop",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [66] = {
        .retval = INT,
        .name  = "semctl",
        .args_value  = {INT, INT, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [67] = {
        .retval = INT,
        .name  = "shmdt",
        .args_value  = {STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [68] = {
        .retval = INT,
        .name  = "msgget",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [69] = {
        .retval = INT,
        .name  = "msgsnd",
        .args_value  = {INT, PTR, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [70] = {
        .retval = INT,
        .name  = "msgrcv",
        .args_value  = {INT, PTR, INT, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [71] = {
        .retval = INT,
        .name  = "msgctl",
        .args_value  = {INT, INT, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [72] = {
        .retval = INT,
        .name  = "fcntl",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [73] = {
        .retval = INT,
        .name  = "flock",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [74] = {
        .retval = INT,
        .name  = "fsync",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [75] = {
        .retval = INT,
        .name  = "fdatasync",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [76] = {
        .retval = INT,
        .name  = "truncate",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [77] = {
        .retval = INT,
        .name  = "ftruncate",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [78] = {
        .retval = INT,
        .name  = "getdents",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [79] = {
        .retval = INT,
        .name  = "getcwd",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [80] = {
        .retval = INT,
        .name  = "chdir",
        .args_value  = {STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [81] = {
        .retval = INT,
        .name  = "fchdir",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [82] = {
        .retval = INT,
        .name  = "rename",
        .args_value  = {STR, STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [83] = {
        .retval = INT,
        .name  = "mkdir",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [84] = {
        .retval = INT,
        .name  = "rmdir",
        .args_value  = {STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [85] = {
        .retval = INT,
        .name  = "creat",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [86] = {
        .retval = INT,
        .name  = "link",
        .args_value  = {STR, STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [87] = {
        .retval = INT,
        .name  = "unlink",
        .args_value  = {STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [88] = {
        .retval = INT,
        .name  = "symlink",
        .args_value  = {STR, STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [89] = {
        .retval = INT,
        .name  = "readlink",
        .args_value  = {STR, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [90] = {
        .retval = INT,
        .name  = "chmod",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [91] = {
        .retval = INT,
        .name  = "fchmod",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [92] = {
        .retval = INT,
        .name  = "chown",
        .args_value  = {STR, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [93] = {
        .retval = INT,
        .name  = "fchown",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [94] = {
        .retval = INT,
        .name  = "lchown",
        .args_value  = {STR, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [95] = {
        .retval = INT,
        .name  = "umask",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [96] = {
        .retval = INT,
        .name  = "gettimeofday",
        .args_value  = {PTR, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [97] = {
        .retval = INT,
        .name  = "getrlimit",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [98] = {
        .retval = INT,
        .name  = "getrusage",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [99] = {
        .retval = INT,
        .name  = "sysinfo",
        .args_value  = {PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [100] = {
        .retval = INT,
        .name  = "times",
        .args_value  = {PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [101] = {
        .retval = INT,
        .name  = "ptrace",
        .args_value  = {INT, INT, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [102] = {
        .retval = INT,
        .name  = "getuid",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [103] = {
        .retval = INT,
        .name  = "syslog",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [104] = {
        .retval = INT,
        .name  = "getgid",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [105] = {
        .retval = INT,
        .name  = "setuid",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [106] = {
        .retval = INT,
        .name  = "setgid",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [107] = {
        .retval = INT,
        .name  = "geteuid",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [108] = {
        .retval = INT,
        .name  = "getegid",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [109] = {
        .retval = INT,
        .name  = "setpgid",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [110] = {
        .retval = INT,
        .name  = "getppid",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [111] = {
        .retval = INT,
        .name  = "getpgrp",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [112] = {
        .retval = INT,
        .name  = "setsid",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [113] = {
        .retval = INT,
        .name  = "setreuid",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [114] = {
        .retval = INT,
        .name  = "setregid",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [115] = {
        .retval = INT,
        .name  = "getgroups",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [116] = {
        .retval = INT,
        .name  = "setgroups",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [117] = {
        .retval = INT,
        .name  = "setresuid",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [118] = {
        .retval = INT,
        .name  = "getresuid",
        .args_value  = {PTR, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [119] = {
        .retval = INT,
        .name  = "setresgid",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [120] = {
        .retval = INT,
        .name  = "getresgid",
        .args_value  = {PTR, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [121] = {
        .retval = INT,
        .name  = "getpgid",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [122] = {
        .retval = INT,
        .name  = "setfsuid",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [123] = {
        .retval = INT,
        .name  = "setfsgid",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [124] = {
        .retval = INT,
        .name  = "getsid",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [125] = {
        .retval = INT,
        .name  = "capget",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [126] = {
        .retval = INT,
        .name  = "capset",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [127] = {
        .retval = INT,
        .name  = "rt_sigpending",
        .args_value  = {PTR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [128] = {
        .retval = INT,
        .name  = "rt_sigtimedwait",
        .args_value  = {PTR, PTR, PTR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [129] = {
        .retval = INT,
        .name  = "rt_sigqueueinfo",
        .args_value  = {INT, INT, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [130] = {
        .retval = INT,
        .name  = "rt_sigsuspend",
        .args_value  = {PTR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [131] = {
        .retval = INT,
        .name  = "sigaltstack",
        .args_value  = {PTR, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [132] = {
        .retval = INT,
        .name  = "utime",
        .args_value  = {STR, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [133] = {
        .retval = INT,
        .name  = "mknod",
        .args_value  = {STR, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [134] = {
        .retval = INT,
        .name  = "uselib",
        .args_value  = {STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [135] = {
        .retval = INT,
        .name  = "personality",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [136] = {
        .retval = INT,
        .name  = "ustat",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [137] = {
        .retval = INT,
        .name  = "statfs",
        .args_value  = {STR, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [138] = {
        .retval = INT,
        .name  = "fstatfs",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [139] = {
        .retval = INT,
        .name  = "sysfs",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [140] = {
        .retval = INT,
        .name  = "getpriority",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [141] = {
        .retval = INT,
        .name  = "setpriority",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [142] = {
        .retval = INT,
        .name  = "sched_setparam",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [143] = {
        .retval = INT,
        .name  = "sched_getparam",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [144] = {
        .retval = INT,
        .name  = "sched_setscheduler",
        .args_value  = {INT, INT, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [145] = {
        .retval = INT,
        .name  = "sched_getscheduler",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [146] = {
        .retval = INT,
        .name  = "sched_get_priority_max",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [147] = {
        .retval = INT,
        .name  = "sched_get_priority_min",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [148] = {
        .retval = INT,
        .name  = "sched_rr_get_interval",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [149] = {
        .retval = INT,
        .name  = "mlock",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [150] = {
        .retval = INT,
        .name  = "munlock",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [151] = {
        .retval = INT,
        .name  = "mlockall",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [152] = {
        .retval = INT,
        .name  = "munlockall",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [153] = {
        .retval = INT,
        .name  = "vhangup",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [154] = {
        .retval = INT,
        .name  = "modify_ldt",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [155] = {
        .retval = INT,
        .name  = "pivot_root",
        .args_value  = {STR, STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [156] = {
        .retval = INT,
        .name  = "_sysctl",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [157] = {
        .retval = INT,
        .name  = "prctl",
        .args_value  = {INT, INT, INT, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [158] = {
        .retval = INT,
        .name  = "arch_prctl",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [159] = {
        .retval = INT,
        .name  = "adjtimex",
        .args_value  = {PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [160] = {
        .retval = INT,
        .name  = "setrlimit",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [161] = {
        .retval = INT,
        .name  = "chroot",
        .args_value  = {STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [162] = {
        .retval = INT,
        .name  = "sync",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [163] = {
        .retval = INT,
        .name  = "acct",
        .args_value  = {STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [164] = {
        .retval = INT,
        .name  = "settimeofday",
        .args_value  = {PTR, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [165] = {
        .retval = INT,
        .name  = "mount",
        .args_value  = {STR, STR, STR, INT, PTR, NULLVAL},
        .nb_args = 5,
    },
    [166] = {
        .retval = INT,
        .name  = "umount2",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [167] = {
        .retval = INT,
        .name  = "swapon",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [168] = {
        .retval = INT,
        .name  = "swapoff",
        .args_value  = {STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [169] = {
        .retval = INT,
        .name  = "reboot",
        .args_value  = {INT, INT, INT, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [170] = {
        .retval = INT,
        .name  = "sethostname",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [171] = {
        .retval = INT,
        .name  = "setdomainname",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [172] = {
        .retval = INT,
        .name  = "iopl",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [173] = {
        .retval = INT,
        .name  = "ioperm",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [174] = {
        .retval = INT,
        .name  = "create_module",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [175] = {
        .retval = INT,
        .name  = "init_module",
        .args_value  = {PTR, INT, STR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [176] = {
        .retval = INT,
        .name  = "delete_module",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [177] = {
        .retval = INT,
        .name  = "get_kernel_syms",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [178] = {
        .retval = INT,
        .name  = "query_module",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [179] = {
        .retval = INT,
        .name  = "quotactl",
        .args_value  = {INT, STR, INT, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [180] = {
        .retval = INT,
        .name  = "nfsservctl",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [181] = {
        .retval = INT,
        .name  = "getpmsg",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [182] = {
        .retval = INT,
        .name  = "putpmsg",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [183] = {
        .retval = INT,
        .name  = "afs_syscall",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [184] = {
        .retval = INT,
        .name  = "tuxcall",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [185] = {
        .retval = INT,
        .name  = "security",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [186] = {
        .retval = INT,
        .name  = "gettid",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [187] = {
        .retval = INT,
        .name  = "readahead",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [188] = {
        .retval = INT,
        .name  = "setxattr",
        .args_value  = {STR, STR, PTR, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [189] = {
        .retval = INT,
        .name  = "lsetxattr",
        .args_value  = {STR, STR, PTR, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [190] = {
        .retval = INT,
        .name  = "fsetxattr",
        .args_value  = {INT, STR, PTR, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [191] = {
        .retval = INT,
        .name  = "getxattr",
        .args_value  = {STR, STR, PTR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [192] = {
        .retval = INT,
        .name  = "lgetxattr",
        .args_value  = {STR, STR, PTR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [193] = {
        .retval = INT,
        .name  = "fgetxattr",
        .args_value  = {INT, STR, PTR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [194] = {
        .retval = INT,
        .name  = "listxattr",
        .args_value  = {STR, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [195] = {
        .retval = INT,
        .name  = "llistxattr",
        .args_value  = {STR, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [196] = {
        .retval = INT,
        .name  = "flistxattr",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [197] = {
        .retval = INT,
        .name  = "removexattr",
        .args_value  = {STR, STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [198] = {
        .retval = INT,
        .name  = "lremovexattr",
        .args_value  = {STR, STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [199] = {
        .retval = INT,
        .name  = "fremovexattr",
        .args_value  = {INT, STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [200] = {
        .retval = INT,
        .name  = "tkill",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [201] = {
        .retval = INT,
        .name  = "time",
        .args_value  = {PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [202] = {
        .retval = INT,
        .name  = "futex",
        .args_value  = {PTR, INT, INT, PTR, PTR, INT},
        .nb_args = 6,
    },
    [203] = {
        .retval = INT,
        .name  = "sched_setaffinity",
        .args_value  = {INT, INT, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [204] = {
        .retval = INT,
        .name  = "sched_getaffinity",
        .args_value  = {INT, INT, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [205] = {
        .retval = INT,
        .name  = "set_thread_area",
        .args_value  = {PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [206] = {
        .retval = INT,
        .name  = "io_setup",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [207] = {
        .retval = INT,
        .name  = "io_destroy",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [208] = {
        .retval = INT,
        .name  = "io_getevents",
        .args_value  = {INT, INT, INT, PTR, PTR, NULLVAL},
        .nb_args = 5,
    },
    [209] = {
        .retval = INT,
        .name  = "io_submit",
        .args_value  = {INT, INT, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [210] = {
        .retval = INT,
        .name  = "io_cancel",
        .args_value  = {INT, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [211] = {
        .retval = INT,
        .name  = "get_thread_area",
        .args_value  = {PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [212] = {
        .retval = INT,
        .name  = "lookup_dcookie",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [213] = {
        .retval = INT,
        .name  = "epoll_create",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [214] = {
        .retval = INT,
        .name  = "epoll_ctl_old",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [215] = {
        .retval = INT,
        .name  = "epoll_wait_old",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [216] = {
        .retval = INT,
        .name  = "remap_file_pages",
        .args_value  = {INT, INT, INT, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [217] = {
        .retval = INT,
        .name  = "getdents64",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [218] = {
        .retval = INT,
        .name  = "set_tid_address",
        .args_value  = {PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [219] = {
        .retval = INT,
        .name  = "restart_syscall",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [220] = {
        .retval = INT,
        .name  = "semtimedop",
        .args_value  = {INT, PTR, INT, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [221] = {
        .retval = INT,
        .name  = "fadvise64",
        .args_value  = {INT, INT, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [222] = {
        .retval = INT,
        .name  = "timer_create",
        .args_value  = {INT, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [223] = {
        .retval = INT,
        .name  = "timer_settime",
        .args_value  = {INT, INT, PTR, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [224] = {
        .retval = INT,
        .name  = "timer_gettime",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [225] = {
        .retval = INT,
        .name  = "timer_getoverrun",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [226] = {
        .retval = INT,
        .name  = "timer_delete",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [227] = {
        .retval = INT,
        .name  = "clock_settime",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [228] = {
        .retval = INT,
        .name  = "clock_gettime",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [229] = {
        .retval = INT,
        .name  = "clock_getres",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [230] = {
        .retval = INT,
        .name  = "clock_nanosleep",
        .args_value  = {INT, INT, PTR, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [231] = {
        .retval = INT,
        .name  = "exit_group",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [232] = {
        .retval = INT,
        .name  = "epoll_wait",
        .args_value  = {INT, PTR, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [233] = {
        .retval = INT,
        .name  = "epoll_ctl",
        .args_value  = {INT, INT, INT, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [234] = {
        .retval = INT,
        .name  = "tgkill",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [235] = {
        .retval = INT,
        .name  = "utimes",
        .args_value  = {STR, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [236] = {
        .retval = INT,
        .name  = "vserver",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [237] = {
        .retval = INT,
        .name  = "mbind",
        .args_value  = {INT, INT, INT, PTR, INT, INT},
        .nb_args = 6,
    },
    [238] = {
        .retval = INT,
        .name  = "set_mempolicy",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [239] = {
        .retval = INT,
        .name  = "get_mempolicy",
        .args_value  = {PTR, PTR, INT, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [240] = {
        .retval = INT,
        .name  = "mq_open",
        .args_value  = {STR, INT, INT, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [241] = {
        .retval = INT,
        .name  = "mq_unlink",
        .args_value  = {STR, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [242] = {
        .retval = INT,
        .name  = "mq_timedsend",
        .args_value  = {INT, STR, INT, INT, PTR, NULLVAL},
        .nb_args = 5,
    },
    [243] = {
        .retval = INT,
        .name  = "mq_timedreceive",
        .args_value  = {INT, STR, INT, PTR, PTR, NULLVAL},
        .nb_args = 5,
    },
    [244] = {
        .retval = INT,
        .name  = "mq_notify",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [245] = {
        .retval = INT,
        .name  = "mq_getsetattr",
        .args_value  = {INT, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [246] = {
        .retval = INT,
        .name  = "kexec_load",
        .args_value  = {INT, INT, PTR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [247] = {
        .retval = INT,
        .name  = "waitid",
        .args_value  = {INT, INT, PTR, INT, PTR, NULLVAL},
        .nb_args = 5,
    },
    [248] = {
        .retval = INT,
        .name  = "add_key",
        .args_value  = {STR, STR, PTR, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [249] = {
        .retval = INT,
        .name  = "request_key",
        .args_value  = {STR, STR, STR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [250] = {
        .retval = INT,
        .name  = "keyctl",
        .args_value  = {INT, INT, INT, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [251] = {
        .retval = INT,
        .name  = "ioprio_set",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [252] = {
        .retval = INT,
        .name  = "ioprio_get",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [253] = {
        .retval = INT,
        .name  = "inotify_init",
        .args_value  = {NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 0,
    },
    [254] = {
        .retval = INT,
        .name  = "inotify_add_watch",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [255] = {
        .retval = INT,
        .name  = "inotify_rm_watch",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [256] = {
        .retval = INT,
        .name  = "migrate_pages",
        .args_value  = {INT, INT, PTR, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [257] = {
        .retval = INT,
        .name  = "openat",
        .args_value  = {INT, STR, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [258] = {
        .retval = INT,
        .name  = "mkdirat",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [259] = {
        .retval = INT,
        .name  = "mknodat",
        .args_value  = {INT, STR, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [260] = {
        .retval = INT,
        .name  = "fchownat",
        .args_value  = {INT, STR, INT, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [261] = {
        .retval = INT,
        .name  = "futimesat",
        .args_value  = {INT, STR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [262] = {
        .retval = INT,
        .name  = "newfstatat",
        .args_value  = {INT, STR, PTR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [263] = {
        .retval = INT,
        .name  = "unlinkat",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [264] = {
        .retval = INT,
        .name  = "renameat",
        .args_value  = {INT, STR, INT, STR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [265] = {
        .retval = INT,
        .name  = "linkat",
        .args_value  = {INT, STR, INT, STR, INT, NULLVAL},
        .nb_args = 5,
    },
    [266] = {
        .retval = INT,
        .name  = "symlinkat",
        .args_value  = {STR, INT, STR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [267] = {
        .retval = INT,
        .name  = "readlinkat",
        .args_value  = {INT, STR, STR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [268] = {
        .retval = INT,
        .name  = "fchmodat",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [269] = {
        .retval = INT,
        .name  = "faccessat",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [270] = {
        .retval = INT,
        .name  = "pselect6",
        .args_value  = {INT, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [271] = {
        .retval = INT,
        .name  = "ppoll",
        .args_value  = {PTR, INT, PTR, PTR, INT, NULLVAL},
        .nb_args = 5,
    },
    [272] = {
        .retval = INT,
        .name  = "unshare",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [273] = {
        .retval = INT,
        .name  = "set_robust_list",
        .args_value  = {PTR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [274] = {
        .retval = INT,
        .name  = "get_robust_list",
        .args_value  = {INT, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [275] = {
        .retval = INT,
        .name  = "splice",
        .args_value  = {INT, PTR, INT, PTR, INT, INT},
        .nb_args = 6,
    },
    [276] = {
        .retval = INT,
        .name  = "tee",
        .args_value  = {INT, INT, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [277] = {
        .retval = INT,
        .name  = "sync_file_range",
        .args_value  = {INT, INT, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [278] = {
        .retval = INT,
        .name  = "vmsplice",
        .args_value  = {INT, PTR, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [279] = {
        .retval = INT,
        .name  = "move_pages",
        .args_value  = {INT, INT, PTR, PTR, PTR, INT},
        .nb_args = 6,
    },
    [280] = {
        .retval = INT,
        .name  = "utimensat",
        .args_value  = {INT, STR, PTR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [281] = {
        .retval = INT,
        .name  = "epoll_pwait",
        .args_value  = {INT, PTR, INT, INT, PTR, INT},
        .nb_args = 6,
    },
    [282] = {
        .retval = INT,
        .name  = "signalfd",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [283] = {
        .retval = INT,
        .name  = "timerfd_create",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [284] = {
        .retval = INT,
        .name  = "eventfd",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [285] = {
        .retval = INT,
        .name  = "fallocate",
        .args_value  = {INT, INT, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [286] = {
        .retval = INT,
        .name  = "timerfd_settime",
        .args_value  = {INT, INT, PTR, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [287] = {
        .retval = INT,
        .name  = "timerfd_gettime",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [288] = {
        .retval = INT,
        .name  = "accept4",
        .args_value  = {INT, PTR, PTR, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [289] = {
        .retval = INT,
        .name  = "signalfd4",
        .args_value  = {INT, PTR, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [290] = {
        .retval = INT,
        .name  = "eventfd2",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [291] = {
        .retval = INT,
        .name  = "epoll_create1",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [292] = {
        .retval = INT,
        .name  = "dup3",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [293] = {
        .retval = INT,
        .name  = "pipe2",
        .args_value  = {PTR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [294] = {
        .retval = INT,
        .name  = "inotify_init1",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [295] = {
        .retval = INT,
        .name  = "preadv",
        .args_value  = {INT, PTR, INT, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [296] = {
        .retval = INT,
        .name  = "pwritev",
        .args_value  = {INT, PTR, INT, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [297] = {
        .retval = INT,
        .name  = "rt_tgsigqueueinfo",
        .args_value  = {INT, INT, INT, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [298] = {
        .retval = INT,
        .name  = "perf_event_open",
        .args_value  = {PTR, INT, INT, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [299] = {
        .retval = INT,
        .name  = "recvmmsg",
        .args_value  = {INT, PTR, INT, INT, PTR, NULLVAL},
        .nb_args = 5,
    },
    [300] = {
        .retval = INT,
        .name  = "fanotify_init",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [301] = {
        .retval = INT,
        .name  = "fanotify_mark",
        .args_value  = {INT, INT, INT, INT, STR, NULLVAL},
        .nb_args = 5,
    },
    [302] = {
        .retval = INT,
        .name  = "prlimit64",
        .args_value  = {INT, INT, PTR, PTR, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [303] = {
        .retval = INT,
        .name  = "name_to_handle_at",
        .args_value  = {INT, STR, PTR, PTR, INT, NULLVAL},
        .nb_args = 5,
    },
    [304] = {
        .retval = INT,
        .name  = "open_by_handle_at",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [305] = {
        .retval = INT,
        .name  = "clock_adjtime",
        .args_value  = {INT, PTR, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [306] = {
        .retval = INT,
        .name  = "syncfs",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [307] = {
        .retval = INT,
        .name  = "sendmmsg",
        .args_value  = {INT, PTR, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [308] = {
        .retval = INT,
        .name  = "setns",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [309] = {
        .retval = INT,
        .name  = "getcpu",
        .args_value  = {PTR, PTR, PTR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [310] = {
        .retval = INT,
        .name  = "process_vm_readv",
        .args_value  = {INT, PTR, INT, PTR, INT, INT},
        .nb_args = 6,
    },
    [311] = {
        .retval = INT,
        .name  = "process_vm_writev",
        .args_value  = {INT, PTR, INT, PTR, INT, INT},
        .nb_args = 6,
    },
    [312] = {
        .retval = INT,
        .name  = "kcmp",
        .args_value  = {INT, INT, INT, INT, INT, NULLVAL},
        .nb_args = 5,
    },
    [313] = {
        .retval = INT,
        .name  = "finit_module",
        .args_value  = {INT, STR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [314] = {
        .retval = INT,
        .name  = "sched_setattr",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [315] = {
        .retval = INT,
        .name  = "sched_getattr",
        .args_value  = {INT, PTR, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [316] = {
        .retval = INT,
        .name  = "renameat2",
        .args_value  = {INT, STR, INT, STR, INT, NULLVAL},
        .nb_args = 5,
    },
    [317] = {
        .retval = INT,
        .name  = "seccomp",
        .args_value  = {INT, INT, STR, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [318] = {
        .retval = INT,
        .name  = "getrandom",
        .args_value  = {PTR, PTR, PTR, PTR, PTR, PTR},
        .nb_args = 6,
    },
    [319] = {
        .retval = INT,
        .name  = "memfd_create",
        .args_value  = {STR, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [320] = {
        .retval = INT,
        .name  = "kexec_file_load",
        .args_value  = {INT, INT, INT, STR, INT, NULLVAL},
        .nb_args = 5,
    },
    [321] = {
        .retval = INT,
        .name  = "bpf",
        .args_value  = {INT, PTR, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [322] = {
        .retval = INT,
        .name  = "execveat",
        .args_value  = {INT, STR, PTR, PTR, INT, NULLVAL},
        .nb_args = 5,
    },
    [323] = {
        .retval = INT,
        .name  = "userfaultfd",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    },
    [324] = {
        .retval = INT,
        .name  = "membarrier",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [325] = {
        .retval = INT,
        .name  = "mlock2",
        .args_value  = {INT, INT, INT, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 3,
    },
    [326] = {
        .retval = INT,
        .name  = "copy_file_range",
        .args_value  = {INT, PTR, INT, PTR, INT, INT},
        .nb_args = 6,
    },
    [327] = {
        .retval = INT,
        .name  = "preadv2",
        .args_value  = {INT, PTR, INT, INT, INT, INT},
        .nb_args = 6,
    },
    [328] = {
        .retval = INT,
        .name  = "pwritev2",
        .args_value  = {INT, PTR, INT, INT, INT, INT},
        .nb_args = 6,
    },
    [329] = {
        .retval = INT,
        .name  = "pkey_mprotect",
        .args_value  = {INT, INT, INT, INT, NULLVAL, NULLVAL},
        .nb_args = 4,
    },
    [330] = {
        .retval = INT,
        .name  = "pkey_alloc",
        .args_value  = {INT, INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 2,
    },
    [331] = {
        .retval = INT,
        .name  = "pkey_free",
        .args_value  = {INT, NULLVAL, NULLVAL, NULLVAL, NULLVAL, NULLVAL},
        .nb_args = 1,
    }
};

#endif /* !SYSCALL_VAL_H_ */